apiVersion: v1
entries:
  filebeat:
  - apiVersion: v2
    appVersion: 8.5.1
    created: "2025-05-13T14:58:56.542377735+03:00"
    description: A Helm chart for Kubernetes
    digest: 48cef57aa4b11699f20083bd45275dc4592abe3c8bebeb0a118d37b15e845ea3
    name: filebeat
    type: application
    urls:
    - https://burakbakirdev.github.io/helm-charts/charts/filebeat-0.1.0.tgz
    version: 0.1.0
generated: "2025-05-13T14:58:56.539811111+03:00"
